language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
branches:
  only:
  - master
  
before_script:
 - chmod +x gradlew
 
before_install:
 - chmod +x gradlew
 
after_success:
- ./gradlew build