language: java

jdk:
- oraclejdk8

branches:
  only:
  - headless
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  
before_script:
 - chmod +x gradlew
 
before_install:
 - chmod +x gradlew
 
after_success:
- ./gradlew build